#!/bin/bash
#SBATCH -J package/toolname
#SBATCH -e /scratch/project_*****/name_err.txt
#SBATCH -o /scratch/project_*****/name_out.txt
#SBATCH -t 24:00:00
#SBATCH --account=project_*****
#SBATCH --ntasks=6
#SBATCH --mem-per-cpu=256000
#SBATCH --partition=large
#SBATCH --array=1
#SBATCH --mail-type=END,FAIL,TIME_LIMIT
#SBATCH --mail-user=email_ID

#load module
module load _ _####_ _ 

#your commands continue
